# Generated by Django 2.1.5 on 2019-09-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('items', models.ManyToManyField(blank=True, null=True, related_name='cart', to='orders.Pasta')),
            ],
        ),
    ]
