# Generated by Django 2.1.5 on 2019-09-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
