# Generated by Django 2.1.5 on 2019-09-25 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pizzaprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='size',
        ),
    ]
