# Generated by Django 2.1.5 on 2019-09-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_sub_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('size', models.CharField(choices=[('S', 'SMALL'), ('L', 'LARGE')], max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='sub',
            name='size',
            field=models.CharField(choices=[('S', 'SMALL'), ('L', 'LARGE')], default='S', max_length=10),
            preserve_default=False,
        ),
    ]
