# Generated by Django 2.1.5 on 2019-09-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190925_1320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubOrder',
        ),
    ]
